const test=require('node:test'),assert=require('node:assert/strict');
const {Op}=require('sequelize');const {createExportLifecycle}=require('../services/exportLifecycle');
function match(r,w){return Reflect.ownKeys(w).every(k=>{const v=w[k];if(k===Op.or)return v.some(x=>match(r,x));if(v&&typeof v==='object'&&!(v instanceof Date)){if(Object.hasOwn(v,Op.lt))return r[k]!=null&&Number(r[k])<Number(v[Op.lt]);if(Object.hasOwn(v,Op.ne))return v[Op.ne]===null?r[k]!=null:r[k]!==v[Op.ne];}return v===null?r[k]==null:r[k]===v;});}
function fixture(env={}){let time=100000;const traces=[],rows=[{id:'one',status:'processing',worker_token:'owner',heartbeat_at:new Date(time),created_at:new Date(time),cancel_requested_at:null,progress:51}];const model={findByPk:async id=>rows.find(r=>r.id===id),update:async(data,{where,returning})=>{const changed=rows.filter(r=>match(r,where));for(const r of changed)Object.assign(r,data);return returning?[changed.length,changed]:[changed.length];}};const worker=createExportLifecycle({ExportJob:model,Op,sequelize:{transaction:async fn=>fn({LOCK:{UPDATE:'UPDATE'}})},env:{EXPORT_TIMEOUT_MS:1800000,EXPORT_LEASE_TIMEOUT_MS:90000,...env},now:()=>time,trace:(event,job,detail)=>traces.push({event,detail})});const job={id:'one',workerToken:'owner',createdAt:time,status:'processing',progress:51};worker.register(job);return {rows,model,worker,job,traces,advance:n=>time+=n};}
test('zero-row heartbeat caused by concurrent recovery rejects immediately',async()=>{const h=fixture();try{h.model.update=async()=>{h.rows[0].status='failed';return [0];};await assert.rejects(h.worker.checkpoint(h.job),/lease/);assert.equal(h.job.abort.signal.aborted,true);}finally{h.worker.release(h.job);}});
test('zero-row heartbeat caused by cancellation observes cancel and stops immediately',async()=>{const h=fixture();try{h.model.update=async()=>{h.rows[0].cancel_requested_at=new Date();return [0];};await assert.rejects(h.worker.checkpoint(h.job),/Cancellation/);assert.equal(h.job.cancelRequested,true);}finally{h.worker.release(h.job);}});
test('30-minute recovery invalidates active owner despite a fresh heartbeat and 90-second lease',async()=>{const h=fixture();try{h.advance(1800001);await h.worker.checkpoint(h.job);await h.worker.reconcile();assert.equal(h.rows[0].status,'failed');await assert.rejects(h.worker.checkpoint(h.job),/lease/);}finally{h.worker.release(h.job);}});
test('extended deadline and 90-second lease preserve active owner at 30 minutes',async()=>{const h=fixture({EXPORT_TIMEOUT_MS:7200000});try{h.advance(1800001);await h.worker.checkpoint(h.job);await h.worker.reconcile();assert.equal(h.rows[0].status,'processing');}finally{h.worker.release(h.job);}});

test('90000 lease override is applied while renewal interval stays 2000 milliseconds',()=>{const h=fixture();try{assert.equal(h.worker.leaseMs,90000);assert.equal(h.worker.intervalMs,2000);assert.equal(h.traces.find(t=>t.event==='lifecycle_configured').detail.leaseMs,90000);}finally{h.worker.release(h.job);}});
test('90-second lease rejects a stale owner but not an 89-second-old heartbeat',async()=>{const h=fixture({EXPORT_TIMEOUT_MS:7200000});try{h.advance(89000);await h.worker.reconcile();assert.equal(h.rows[0].status,'processing');h.advance(1001);await h.worker.reconcile();assert.equal(h.rows[0].status,'failed');assert.equal(h.traces.find(t=>t.event==='lease_recovered').detail.recoveryReason,'heartbeat_expired');}finally{h.worker.release(h.job);}});
for(const reason of ['missing','token','terminal'])test('ownership rejects '+reason+' and diagnoses the observed row',async()=>{const h=fixture();try{if(reason==='missing')h.rows.length=0;if(reason==='token')h.rows[0].worker_token='foreign';if(reason==='terminal')h.rows[0].status='failed';await assert.rejects(h.worker.checkpoint(h.job),/lease/);const detail=h.traces.find(t=>t.event==='lease_rejected').detail;assert.equal(detail.ownerRelation,reason==='missing'?'missing_row':reason==='token'?'token_mismatch':'local');}finally{h.worker.release(h.job);}});
test('database SELECT errors do not masquerade as an observed lease mismatch',async()=>{const h=fixture();try{const error=Object.assign(Error('private database error'),{code:'57014'});h.model.findByPk=async()=>{throw error;};await assert.rejects(h.worker.checkpoint(h.job),e=>e===error);assert.equal(h.traces.some(t=>t.event==='lease_rejected'),false);}finally{h.worker.release(h.job);}});
test('fresh-heartbeat deadline recovery explicitly reports total timeout',async()=>{const h=fixture();try{h.advance(1800001);await h.worker.checkpoint(h.job);await h.worker.reconcile();assert.equal(h.traces.find(t=>t.event==='lease_recovered').detail.recoveryReason,'total_timeout');assert.equal(h.traces.find(t=>t.event==='lease_recovered').detail.heartbeatAgeMs,0);}finally{h.worker.release(h.job);}});

test('a recovery process with an older 30-minute setting fences a healthy 120-minute owner',async()=>{const h=fixture({EXPORT_TIMEOUT_MS:7200000});try{const old=createExportLifecycle({ExportJob:h.model,Op,sequelize:{transaction:async fn=>fn({LOCK:{UPDATE:'UPDATE'}})},env:{EXPORT_TIMEOUT_MS:1800000,EXPORT_LEASE_TIMEOUT_MS:90000},now:()=>h.job.createdAt+1800001,trace:()=>{}});h.advance(1800001);await h.worker.checkpoint(h.job);assert.equal(h.worker.timeoutMs,7200000);await old.reconcile();assert.equal(h.rows[0].status,'failed');await assert.rejects(h.worker.checkpoint(h.job),/lease/);}finally{h.worker.release(h.job);}});
test('delayed heartbeat SELECT followed by concurrent recovery is rejected at the fenced update',async()=>{const h=fixture({EXPORT_TIMEOUT_MS:7200000});try{let release;const base=h.model.findByPk;let first=true;h.model.findByPk=async id=>{if(!first)return base(id);first=false;const snapshot={...h.rows[0]};await new Promise(r=>release=r);return snapshot;};const pending=h.worker.checkpoint(h.job);await new Promise(r=>setImmediate(r));h.advance(90001);await h.worker.reconcile();release();await assert.rejects(pending,/lease/);assert.equal(h.rows[0].status,'failed');}finally{h.worker.release(h.job);}});
