import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import ts from 'typescript';
const require=createRequire(import.meta.url);
const root=path.resolve(import.meta.dirname,'../..');
const math=require('../lib/mediaAnimation');
function load(file,deps){const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText)(n=>{if(!(n in deps))throw Error(n);return deps[n]},m,m.exports);return m.exports;}
const jsx={jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})};
const item={id:'text',type:'text',text:'JACK',duration:4,startTime:2,textX:25,textY:70,animationInPreset:'zoom-in',animationInDuration:1.5,animationInAmount:100,animationOutPreset:'fade-out',animationOutDuration:1,animationOutAmount:50};
test('Animation settings recognizes TEXT and reuses existing AnimationTab',()=>{const component=load('frontend/components/editor/SettingsContent.tsx',{'react/jsx-runtime':jsx,'./settings-tabs/BasicTab':{default:'basic'},'./settings-tabs/AnimationTab':{__esModule:true,default:'animation'},'./settings-tabs/TextSettings':{default:'text'}}).default;const tree=component({activeItem:item,activeTab:'Animation'});const animation=tree.props.children[1].props.children;assert.equal(animation.type,'animation');assert.equal(animation.props.item,item)});
test('TEXT uses shared IN/OUT regions with current duration ratios; MEDIA stays eligible',()=>{const run=load('frontend/components/editor/timeline/track/TimelineAnimationRegions.tsx',{'react/jsx-runtime':jsx}).default;const regions=run({item}).props.children;assert.deepEqual(regions.map(x=>x.props.style.width),['37.5%','25%']);assert.ok(run({item:{...item,type:'media',file:{type:'image'}}}));assert.equal(run({item:{...item,type:'media',file:{type:'audio'}}}),null);});
test('reload hydrates all TEXT phase fields, text geometry and styling',async()=>{let result;const run=load('frontend/composables/useLoadTimeline.ts',{react:{useEffect:fn=>fn()},'@/services/timelineService':{timelineService:{getAll:async()=>({items:[{...item,itemType:'TEXT',textContent:item.text,fontFamily:'Georgia',fontSize:44,fontWeight:700,textColor:'#abcdef'}]})}}}).useLoadTimeline;run({projectId:'project',dispatch:a=>{if(a.type==='LOAD_ITEMS_SUCCESS')result=a.payload}});await new Promise(r=>setImmediate(r));for(const key of math.animationFields)assert.equal(result[0][key],item[key]);assert.equal(result[0].textX,25);assert.equal(result[0].fontFamily,'Georgia');});
test('save hook PATCHes TEXT once per setting, queues latest changes, preserves base fields',async()=>{let items=[item];const patches=[];const hooks={useRef:v=>({current:v}),useEffect:fn=>fn(),useState:v=>[v,()=>{}],useCallback:fn=>fn};const run=load('frontend/composables/useAnimationEditor.ts',{react:hooks,'@/lib/mediaAnimation':math,'@/services/timelineService':{timelineService:{updateItem:async(id,p)=>{patches.push(p);return {item:Object.fromEntries(Object.entries(p).map(([k,v])=>[k.replace(/[A-Z]/g,c=>'_'+c.toLowerCase()),v]))}}}}}).useAnimationEditor;const hook=run({projectId:"project",timelineItems:items,setTimelineItems:fn=>items=fn(items)});hook.handleUpdateAnimation(item.id,{animationInAmount:50});hook.handleUpdateAnimation(item.id,{animationOutDuration:2});await new Promise(r=>setImmediate(r));assert.equal(patches.length,2);assert.equal(items[0].animationInAmount,50);assert.equal(items[0].animationOutDuration,2);assert.equal(items[0].textX,25);assert.equal(items[0].fontSize,undefined);assert.ok(!('textX' in patches[0]));});
